name: Test

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.28.2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Arkstack
        run: |
          pnpm install:arkstack
          cd test/arkstack-app
          echo "CWD: $(pwd)"
          pnpm install --ignore-workspace --no-frozen-lockfile
          pnpm prepare || echo "prepare failed with $?"
          find .arkstack -type f | sort || echo ".arkstack does not exist"

      - name: Prepare Arkstack
        run: |
          cd test/arkstack-app
          pnpm prepare || echo "prepare failed with $?"
          find .arkstack -type f | sort || echo ".arkstack does not exist"

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Build
        run: pnpm build

      - name: Test
        env:
          APP_URL: http://localhost:3000
          APP_PORT: 3000
          NODE_ENV: production
        run: pnpm test:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: arkstack-tmp/parasito
